title: "Merritt codes"
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
