title: "Merritt codes"
description: >- # this means to ignore newlines until "baseurl:"
  Personal portfolio for Kristen McWilliam
minimal_mistakes_skin: dark
search: false
baseurl: "/"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
# Outputting
permalink: /:categories/:title/

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name      : "Kristen McWilliam"
  avatar    : "/assets/images/bio-photo.jpg"
  bio       : "Software Developer" # Markdown allowed.
  location  : "Ottawa, Canada"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Merrittkr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Merrit"

defaults:
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: false
      read_time: false
      comments: false
      related: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
